### ISSUE TITLE
Ibland får vi ett fel i CollisionManager 

### ISSUE THREAD

**Issue by simon-f-kevin** [zimme95/thundercats#14]
Vi får felmeddelande "Destination array was not long enough. Check destIndex and length, and the array's lower bounds." i metoden: 
```
public void AddCollisionPair(Entity source, Entity target)
        {
            CurrentCollisionPairs.Enqueue(new Tuple<Entity, Entity>(source, target));
        }
```

https://stackoverflow.com/questions/10362023/destination-array-not-long-enough

**Comment by Axellent** [comment]
Har inte lyckats reproducera så antar att det är hyfsat sällsynt. Har hursomhelst trådsäkrat collision manager så det borde inte uppstå igen
