### ISSUE TITLE
ISSUE WITH WORLD AND AI 

### ISSUE THREAD

**Issue by Mackan95bowling** [zimme95/thundercats#21]
We call the AIsystem Before we generate the World which is a problem cuz we get exception instance == null on worldMatrix in AIsystem just because this... we need to fixure out how to generate world earlier or wait longer with the call to AI

**Comment by xXDragonZlayerXx** [comment]
My suggestion would be to change our SystemManager. We should still have only one instance of each system, but each state should have their own IUpdateableSystems-queue and IDrawableSystems-queue, that way the AI systems Update method will not run until we are inside a playing-state.

**Comment by simon-f-kevin** [comment]
Nick > solution
