### ISSUE TITLE
Collision 

### ISSUE THREAD

**Issue by Mackan95bowling** [zimme95/thundercats#26]
Collision är av faktor STOR! i behov av fixning då kollisionerna stöter bort blobarna när dom är på blocken, vi kommenterade bort alla förutom Y leds kollisionerna och det funkar hyfsat dock kan man inte hoppa när man är på ett block då vi måste fulhacka in att positionen och hastigheten blir = 0

**Comment by simon-f-kevin** [comment]
Någon har fixat detta utan att ta åt sig äran
